### ISSUE TITLE
ScriptPreventResinShrinkage.cs generating layers out-of-order

### ISSUE THREAD

**Issue by doug-harriman** [yaqwsx/UVToolsScripts#4]
The use of the [Parallel For loop](https://github.com/yaqwsx/UVToolsScripts/blob/f24d08b6df90175d17f1266beb4712f389c19eb5/ScriptPreventResinShrinkage.cs#L129) seems to be generating layers out of order.  My file was unprintable due to layers no longer being sorted by height after running script.  I hand modified the script to process layers one at a time using a standard for loop and the issue was resolved.

**Comment by sn4k3** [comment]
That's true, I made some modifications on the code and introduced that bug. I will sove it ASAP.

**Comment by doug-harriman** [comment]
Verified fix correct in UVTools.
